### ISSUE TITLE
Create a dev instance of the QHub deployment

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-qhub#5]
We have a deployment of QHub which currently resides at veda-analytics.delta-backend.com using https://github.com/nasa-impact/veda-qhub and deployed to the UAH AWS environment under the project name "aimee-qhub". 

We want to deploy another instance of this to act as our dev environment. Then we will have a dev environment for testing out changes and a "demo" environment for live demos.

Note we plan to call these jupyter-demo.delta-backend.com and jupyter-dev.delta-backend.com

Acceptance criteria: 
- [ ] A running instance of QHub in the UAH account under the domain jupyter-dev.delta-backend.com that is accessible to members of this team.

**Comment by j08lue** [comment]
No dev deployment planned, as the main deployment we will work with is the SMCE 2i2c one and externally provided services such as MAAP.
